schema_version: 1

context:
  python_min: "3.10"
  version: "1.7.2.20260807"

package:
  name: types-authlib
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/types-authlib/types_authlib-${{ version }}.tar.gz
  sha256: b2f557c15c7447296174d2fb33048ae61dac4b1399a953b6f917b9e8e5995186

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=82.0.1
    - pip
  run:
    - python >=${{ python_min }}
    - cryptography

tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
  - package_contents:
      site_packages:
        - authlib-stubs/__init__.pyi

about:
  summary: Typing stubs for Authlib
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/python/typeshed

extra:
  recipe-maintainers:
    - peterbygrave
